modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="vineryjs"
version="${mod_version}"
displayName="${mod_name}"
authors="MidnightKittens"
description='''KubeJS integration for Vinery.'''
logoFile = "vineryjs.png"

[[mixins]]
config="vineryjs.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.vineryjs]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.vineryjs]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vineryjs]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vineryjs]]
modId="vinery"
type="required"
versionRange="[1.5.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.vineryjs]]
modId="kubejs"
type="required"
versionRange="[2101.7.2,)"
ordering="AFTER"
side="BOTH"